import presenterOne from "@/assets/stationImageOne.jpeg";
import presenterTwo from "@/assets/stationImageTwo.jpeg";
import presenterThree from "@/assets/stationImageThree.jpeg";
import presenterFour from "@/assets/stationImageFour.jpeg";

export const radioScheduler = {
  monday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      present: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
  tuesday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      presenter: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
  wednesday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      present: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
  thursday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      present: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
  friday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      present: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
  saturday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      present: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
  sunday: [
    {
      id: 1,
      title: "Morning Breeze",
      presenter: "Sarah",
      start: "06:00",
      end: "10:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "Midday Mix",
      presenter: "Dj John",
      start: "10:00",
      end: "14:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "Drive time",
      presenter: "Michael",
      start: "14:00",
      end: "18:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "Night Train",
      present: "Daniel",
      start: "18:00",
      end: "06:00",
      image: presenterFour,
    },
  ],
};
