import presenterOne from "@/assets/stationImageOne.jpeg";
import presenterTwo from "@/assets/stationImageTwo.jpeg";
import presenterThree from "@/assets/stationImageThree.jpeg";
import presenterFour from "@/assets/stationImageFour.jpeg";
import newsImage from "@/assets/news.jpeg";

export const radioScheduler = {
  weekday: [
    {
      id: 1,
      title: "GEN MATIN",
      start: "04:00",
      end: "06:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "YAB WANGI MON-FRIDAY",
      start: "06:00",
      end: "10:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "YIN KI TICI",
      start: "10:00",
      end: "13:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "CIRCLE OF FRIENDS",
      start: "13:00",
      end: "16:00",
      image: presenterFour,
    },
    {
      id: 5,
      title: "SPEAK SPORTS",
      start: "16:00",
      end: "17:00",
      image: presenterFour,
    },
    {
      id: 6,
      title: "MA INONGO TIN",
      start: "17:00",
      end: "21:00",
      image: presenterFour,
    },
    {
      id: 7,
      title: "SPORTS GALA",
      start: "21:00",
      end: "23:00",
      image: presenterFour,
    },
  ],
  saturday: [
    {
      id: 1,
      title: "GEN MATIN",
      start: "04:00",
      end: "06:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "PRIME TIME SHOW",
      start: "06:00",
      end: "09:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "OYENG-YENG",
      start: "09:00",
      end: "12:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "CHILDRENS PROGRAM",
      start: "12:00",
      end: "13:00",
      image: presenterFour,
    },
    {
      id: 5,
      title: "MON MA KWIRI WOMENS MAGAZINE",
      start: "13:00",
      end: "15:00",
      image: presenterFour,
    },
    {
      id: 6,
      title: "YOUTH WITH VISION",
      start: "15:00",
      end: "17:00",
      image: presenterFour,
    },
    {
      id: 7,
      title: "SPEAK WEEKEND SPORTS",
      start: "17:00",
      end: "21:00",
      image: presenterFour,
    },
    {
      id: 8,
      title: "NORTHERN CONNECTION",
      start: "21:00",
      end: "24:00",
      image: presenterFour,
    },
  ],
  sunday: [
    {
      id: 1,
      title: "GEN MATIN",
      start: "04:00",
      end: "06:00",
      image: presenterOne,
    },
    {
      id: 2,
      title: "SUNDAY GOSPEL EXPLOSION",
      start: "06:00",
      end: "09:00",
      image: presenterTwo,
    },
    {
      id: 3,
      title: "KWAN BER",
      start: "09:00",
      end: "11:00",
      image: presenterThree,
    },
    {
      id: 4,
      title: "COMMUNITY CONNECT",
      start: "11:00",
      end: "14:00",
      image: presenterFour,
    },
    {
      id: 5,
      title: "SPEAK TOP 20 COUNT DOWN",
      start: "14:00",
      end: "16:00",
      image: presenterFour,
    },
    {
      id: 6,
      title: "FARMERS CORNER",
      start: "16:00",
      end: "17:00",
      image: presenterFour,
    },
    {
      id: 7,
      title: "SPEAK WEEKEND SPORTS",
      start: "17:00",
      end: "20:00",
      image: presenterFour,
    },
    {
      id: 8,
      title: "NENO MATUT-COMMUNITY DEBATE",
      start: "20:00",
      end: "21:00",
      image: presenterFour,
    },
  ],
  news: {
    weekday: [
      {
        id: 1,
        title: "LUO NEWS",
        start: "07:00",
        end: "07:15",
        image: newsImage,
      },
      {
        id: 2,
        title: "ENGLISH NEWS",
        start: "08:00",
        end: "08:10",
        image: newsImage,
      },
      {
        id: 3,
        title: "ENGLISH NEWS",
        start: "10:00",
        end: "10:10",
        image: newsImage,
      },
      {
        id: 4,
        title: "LOU NEWS",
        start: "11:00",
        end: "11:15",
        image: newsImage,
      },
      {
        id: 5,
        title: "LUO NEWS",
        start: "13:00",
        end: "13:15",
        image: newsImage,
      },
      {
        id: 6,
        title: "ENGLISH NEWS",
        start: "14:00",
        end: "14:10",
        image: newsImage,
      },
      {
        id: 7,
        title: "LUO NEWS",
        start: "19:00",
        end: "19:15",
        image: newsImage,
      },
      {
        id: 8,
        title: "ENGLISH NEWS",
        start: "20:00",
        end: "20:10",
        image: newsImage,
      },
    ],

    saturday: [
      {
        id: 1,
        title: "ENGLISH NEWS",
        start: "07:00",
        end: "07:10",
        image: newsImage,
      },
      {
        id: 2,
        title: "LUO NEWS",
        start: "08:00",
        end: "08:15",
        image: newsImage,
      },
      {
        id: 3,
        title: "ENGLISH NEWS",
        start: "13:00",
        end: "13:10",
        image: newsImage,
      },
      {
        id: 4,
        title: "LUO NEWS",
        start: "14:00",
        end: "14:15",
        image: newsImage,
      },
      {
        id: 5,
        title: "LUO NEWS",
        start: "19:00",
        end: "19:15",
        image: newsImage,
      },
      {
        id: 6,
        title: "ENGLISH NEWS",
        start: "20:00",
        end: "20:10",
        image: newsImage,
      },
    ],

    sunday: [
      {
        id: 1,
        title: "ENGLISH NEWS",
        start: "07:00",
        end: "07:10",
        image: newsImage,
      },
      {
        id: 2,
        title: "LOU NEWS",
        start: "08:00",
        end: "08:15",
        image: newsImage,
      },
      {
        id: 3,
        title: "WEEKLY NEWS ROUND UP",
        start: "21:00",
        end: "21:30",
        image: newsImage,
      },
    ],
  },
};
